version: '3.8'
services:
  # Ollama service - Local LLM server
  ollama:
    image: ollama/ollama
    container_name: llm_ollama
    networks:
      - llm_network
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Open WebUI - Web interface for Ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: llm_open-webui
    networks:
      - llm_network
    volumes:
      - webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      ollama:
        condition: service_healthy

networks:
  llm_network:
    driver: bridge
    name: llm_network

volumes:
  ollama_data:
    name: llm_ollama_data
  webui_data:
    name: llm_webui_data
